### ISSUE TITLE
Async tasks don't get executed when in the background for 5mins (Cordova/Android) [$120]

### ISSUE THREAD

**Issue by jxxmin** [jxxmin/backgroundTest#1]
I am developping a music player app with react and cordova using the official cordova media plugin. Whenever a track is finished, the success callback gets executed, where the next track should get fetched. This is an asynchronous javascript operation.

However, after being approximately 5 mins in the background, the app doesn't execute the asnychronous tasks anymore and just hangs. If there is only "normal" javascript in the callback and no awaits, it executes without problems even in the background.

To demonstrate the problem, I created this mini test app that shows the same behaviour. See the README of the project for a detailed description.

**Comment by BonifacioCalindoro** [comment]
Hello, I saw your bounty and I wanted to give it a try, but as I prefer to be helpful than greedy: have you tried adding lines like  "await asyncio.sleep(0.5)" in the 'PlayTrack' function? Obviously the playtrack function should be async for this to work, and maybe I'm completely wrong about this, but I had a similar problem last week, and it got solved by just making the async functions sleep a little every now and then (it was in python so maybe completely unrelated problem). 

I'm thinking that putting a music playing function to sleep every X seconds could be very problematic, but I'd need to see that function to be sure.

I hope I helped you in some way, and if I haven't, I'd like to try again 😀

**Comment by BonifacioCalindoro** [comment]
Mm I re-read the readme and maybe I rushed to comment without properly interpreting the problem. So if the musicplaying function works perfectly, is it the main background loop that is hanging when no interaction? Then I'd add these asyncio sleep to that background functions, probably longer than 0.5 maybe 5-10

**Comment by jcfgh** [comment]
Hello,

Have you try to use the wakeup method?

const timer = 4*60*1000;
 this.backgroundMode.enable();
 this.backgroundMode.on('activate')
    .subscribe(()=>{
       setInterval(()=>{
            this.backgroundMode.wakeUp();
            this.backgroundMode.moveToForeground();
          },timer);
    });

**Comment by jcfgh** [comment]
Hi.

You can use a plugin [https://github.com/katzer/cordova-plugin-background-mode]( https://github.com/katzer/cordova-plugin-background-mode)

and then

```
const timer = 4*60*1000; // four minutes
 this.backgroundMode.enable();
 this.backgroundMode.on('activate')
    .subscribe(()=>{
       setInterval(()=>{
            this.backgroundMode.wakeUp();
            this.backgroundMode.moveToForeground();
          },timer);
    });
```

**Comment by jcfgh** [comment]
Hi.

You can use the plugin [https://github.com/katzer/cordova-plugin-background-mode](https://github.com/katzer/cordova-plugin-background-mode)

and then

```
const timer = 4*60*1000; // four minutes
 this.backgroundMode.enable();
 this.backgroundMode.on('activate')
    .subscribe(()=>{
       setInterval(()=>{
            this.backgroundMode.wakeUp();
            this.backgroundMode.moveToForeground();
          },timer);
    });
```

**Comment by jcfgh** [comment]
Hi.

You can use the plugin [https://github.com/katzer/cordova-plugin-background-mode](https://github.com/katzer/cordova-plugin-background-mode) or try [https://github.com/pinguluk/ionic-native-background-mode
](https://github.com/pinguluk/ionic-native-background-mode
)
and then

```
const timer = 4*60*1000; // four minutes
 this.backgroundMode.enable();
 this.backgroundMode.on('activate')
    .subscribe(()=>{
       setInterval(()=>{
            this.backgroundMode.wakeUp();
            this.backgroundMode.moveToForeground();
          },timer);
    });
```

**Comment by dorian-hart-ferrer** [comment]
Hi,

Do you know what android image you are building to?

When I build to `system-images;android-33;google_apis;x86_64` and run the emulator on my computer, the sound plays well passed 5 minutes.

I installed this image via `sdkmanager --install "
system-images;android-33;google_apis;x86_64"`

**Comment by andeodev** [comment]
This is now solved, but it was quite a ride.

The famous [cordova-plugin-background-mode](https://github.com/katzer/cordova-plugin-background-mode) allows to run code in the background, but it hasn't been updated since 2019 and doesn't even compile anymore with modern SDK versions. But even when these issues are fixed (see pending PRs), it just does not work in this particular instance, for reasons I didn't investigate further. In essence, this plugin creates a [foreground service](https://developer.android.com/guide/components/foreground-services), which allows an app to continue to do immediate work, despite being in the background. For this to work, Android requires the app to display a notification while doing so.

The [cordova-plugin-music-controls2](https://github.com/ghenry22/cordova-plugin-music-controls2) that is already present in the project is supposed to do the exact same thing as the background mode plugin. Therefore, in theory, there would be no need to have both. It also creates a foreground service, but its use-case is specifically tuned for music players. In particular, the mandatory notification contains the play/pause buttons that one is likely to want anyway. For some reason, that plugin works for some people, but just fails to do its job in this particular case.

Interestingly, adding both plugins at the same time seems to fix the issue, even though one of the plugins should be enough. This means that they each partially do what is necessary to make the app continue to run in the background and only the combination of both does it successfully. Using both plugins is not a good solution though, as that would result in two notifications. The better solution was to compare the two plugins and see how they differ and copy the missing parts over to the other. I forked the music controls plugin and add some code to it. The most relevant line of code is this:

    // called in the onPause() method
    view.dispatchWindowVisibilityChanged(View.VISIBLE);

`onPause()` is called when the app is moved to the background and is no longer visible. By default, the Android views are being notified about this and the Android web view will pause JavaScript execution as a consequence. This is why no macro tasks will be executed anymore (although, any code submitted using `evaluateJavascript()` would still execute, which made debugging quite confusing). This code just notifies the web view that it is in the foreground again, even when it isn't. Yes it's a bit of a hack, but it works. [The forked plugin can be viewed here.](https://github.com/andeodev/cordova-plugin-music-controls2)

I plan to submit useful PRs to the original music control plugin in due time, especially the typescript support I added in the process.

**Comment by makeasnek** [comment]
Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues

**Comment by KushalSr** [comment]
Is this issue is open?

**Comment by ghost** [comment]
- https://github.com/bountysource/core/issues/1586
